### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by bennyn** [bennyn/generator-toe#5]
On Linux:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/lib/node_modules/generator-toe/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/usr/lib/node_modules/generator-toe/node_modules/mem-fs-editor/actions/copy.js:44:3)
    at EditionInterface.exports.copy (/usr/lib/node_modules/generator-toe/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at module.exports.yeoman.generators.Base.extend.writing.writeRootFiles (/usr/lib/node_modules/generator-toe/generators/app/index.js:165:15)
    at /usr/lib/node_modules/generator-toe/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)```
```

On Windows:

![image](https://cloud.githubusercontent.com/assets/469989/11063582/025a3984-87b8-11e5-984d-e0ebf22bf512.png)

**Comment by bennyn** [comment]
Global node module `generator-toe` has been installed to `%APPDATA%\npm\node_modules\generator-toe` which resolves to `...\AppData\Roaming\npm\node_modules\generator-toe`.

**Comment by bennyn** [comment]
Looks like `.gitignore` files are filtered in npm packages like:
http://registry.npmjs.org/generator-toe/-/generator-toe-0.2.1.tgz

**Comment by bennyn** [comment]
Fixed with https://github.com/bennyn/generator-toe/commit/0d3b48e6d111e40a57c715760a9afd7d72864ca1
